services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=chernov-elk-cluster
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.18
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - elasticsearch
      - nginx
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.18
    container_name: filebeat
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./nginx/logs:/var/log/nginx:ro
    depends_on:
      - elasticsearch
      - nginx
    networks:
      - elk

networks:
  elk:
    driver: bridge